-- Reconciliation: raw-SQL production changes made after the last Prisma
-- migration (20260323000000_add_waitlist_request).
--
-- Every statement is IF NOT EXISTS. Against production, where all of these
-- objects already exist, this is a no-op and is marked applied with
-- `prisma migrate resolve --applied`. Against a fresh database it creates
-- them, so migrations alone reproduce the production structure.
--
-- Generated by scripts/build-reconciliation-sql.js from the application code
-- that originally issued this DDL. Verify against `prisma db pull`.

CREATE TABLE IF NOT EXISTS newsletter_issues (
  id TEXT PRIMARY KEY,
  issue_number INT NOT NULL,
  slug TEXT NOT NULL,
  subject TEXT NOT NULL,
  preview TEXT,
  web_html TEXT,
  sent_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  source TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

CREATE TABLE IF NOT EXISTS website_events (
  id TEXT PRIMARY KEY,
  viewer_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  path TEXT NOT NULL,
  referrer TEXT,
  duration_ms INTEGER,
  scroll_depth INTEGER,
  event_value TEXT,
  metadata_json TEXT,
  user_agent TEXT,
  ip_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

CREATE TABLE IF NOT EXISTS "Testimonial" (
  id TEXT PRIMARY KEY,
  quote TEXT NOT NULL,
  author_name TEXT NOT NULL,
  author_title TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

CREATE TABLE IF NOT EXISTS "WaitlistRequest" (
  "id" TEXT NOT NULL,
  "zip" TEXT NOT NULL,
  "contactEmail" TEXT,
  "contactPhone" TEXT,
  "timeline" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "WaitlistRequest_pkey" PRIMARY KEY ("id")
  );

CREATE TABLE IF NOT EXISTS "DischargeReferral" (
  "id" TEXT NOT NULL,
  "planner_name" TEXT,
  "planner_title" TEXT,
  "planner_email" TEXT,
  "planner_phone" TEXT,
  "facility" TEXT,
  "patient_first" TEXT,
  "patient_last" TEXT,
  "patient_zip" TEXT,
  "care_type" TEXT,
  "urgency" TEXT,
  "insurance" TEXT,
  "notes" TEXT,
  "status" TEXT NOT NULL DEFAULT 'new',
  "source" TEXT NOT NULL DEFAULT 'discharge_planner',
  "submitted_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "DischargeReferral_pkey" PRIMARY KEY ("id")
  );

CREATE TABLE IF NOT EXISTS "JobLead" (
  "id" TEXT NOT NULL,
  "zip" TEXT NOT NULL,
  "name" TEXT,
  "email" TEXT,
  "phone" TEXT,
  "role" TEXT,
  "licensed" TEXT,
  "availability" TEXT,
  "timeline" TEXT,
  "experience" TEXT,
  "openToMultiple" TEXT,
  "notifiedProviderIds" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "JobLead_pkey" PRIMARY KEY ("id")
  );

ALTER TABLE "Testimonial" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'approved';

ALTER TABLE "Testimonial" ADD COLUMN IF NOT EXISTS "provider_id" TEXT;

ALTER TABLE "Testimonial" ADD COLUMN IF NOT EXISTS "reviewed_at" TIMESTAMPTZ;

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "activelyHiring" BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "receiveClientLeads" BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "receiveJobLeads" BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "sessionId" TEXT;

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "stripeCustomerId" TEXT;

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "stripeSubscriptionId" TEXT;

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "subscriptionStatus" TEXT;

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "currentPeriodEnd" TIMESTAMP;

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "billingMode" TEXT NOT NULL DEFAULT 'free';

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "subscriptionMonthlyCents" INTEGER;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "adminStatus" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "adminProviderId" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "gclid" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "fbclid" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "firstChannel" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "firstSource" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "firstMedium" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "firstCampaign" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "firstTerm" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "firstContent" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "firstLandingPage" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "firstReferrer" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "firstTouchAt" TIMESTAMPTZ;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lastChannel" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lastSource" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lastMedium" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lastCampaign" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lastTerm" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lastContent" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lastLandingPage" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lastReferrer" TEXT;

ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lastTouchAt" TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS idx_newsletter_issues_slug ON newsletter_issues(slug);

CREATE INDEX IF NOT EXISTS idx_newsletter_subscribers_email ON newsletter_subscribers(email);

CREATE INDEX IF NOT EXISTS idx_website_events_created_at ON website_events(created_at);

CREATE INDEX IF NOT EXISTS idx_website_events_event_type ON website_events(event_type);

CREATE INDEX IF NOT EXISTS idx_website_events_viewer_id ON website_events(viewer_id);

CREATE INDEX IF NOT EXISTS idx_website_events_session_id ON website_events(session_id);

CREATE INDEX IF NOT EXISTS idx_lead_session_id ON "Lead"("sessionId");

CREATE INDEX IF NOT EXISTS idx_lead_first_channel ON "Lead"("firstChannel");
